### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

### ISSUE THREAD

**Issue by GF-Huang** [Nongzhsh/Awesome.Net.WritableOptions#1]

**Comment by nogic1008** [comment]
[Microsoft.Extensions.Configuration.Json](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/) is no longer using Newtonsoft.Json.
So we need to add a direct dependency on Newtonsoft.Json, or migrate to System.Text.Json.
