### ISSUE TITLE
src/Awesome.Net.WritableOptions/Extensions/ServiceCollectionExtensions.cs

### ISSUE THREAD

**Issue by VAllens** [Nongzhsh/Awesome.Net.WritableOptions#2]
```chsarp
public static void ConfigureWritableOptions<T>(this IServiceCollection services, IConfigurationSection section, string subPathOfFile = "appsettings.json") where T : class, new();
```

这个接口，应该将参数 `section` 的类型 `IConfigurationSection` 改成 `IConfiguration`

**Comment by Nongzhsh** [comment]
> 这个接口，应该将参数 section 的类型 IConfigurationSection 改成 IConfiguration

这里即将配置具体节点，传入 IConfigurationSection 是合理的

**Comment by VAllens** [comment]
> > 这个接口，应该将参数 section 的类型 IConfigurationSection 改成 IConfiguration
> 
> 这里即将配置具体节点，传入 IConfigurationSection 是合理的

如果`subPathOfFile`参数配的是独立的json文件，泛型参数`T`是这个json文件的`根类型`。
`section`参数应该如何传？

**Comment by Nongzhsh** [comment]
> 如果`subPathOfFile`参数配的是独立的json文件，泛型参数`T`是这个json文件的`根类型`。 `section`参数应该如何传？

在新的提交中已经重构了

**Comment by VAllens** [comment]
good...
